---
- hosts: all
  gather_facts: True
  sudo: yes
  vars_files:
    - vars.yml
  tasks:
    - name: system packages
      yum: pkg={{ item }} state=installed
    # yum: pkg={{ item }} state=latest
      with_items: system_packages
    - name: npm packages
      shell: "npm install -g {{ item }}" 
      with_items: npm_packages
    - name: gem update
      shell: "gem update --system"
    - name: install gems
      shell: "gem install {{ item }} " 
      with_items: gem_packages 
    - name: clone workshop repo
      git: repo=https://github.com/edthedev/TddJavaScriptWorkshop.git dest={{ project_home }}
    - name: install workshop
      shell: "cd {{ project_home }}; npm install"
      notify: 
        - verify_install
        - serve_app
  handlers:
    - name: verify_install
      shell: "cd {{ project_home }}; gulp"
    - name: serve_app
      shell: "cd {{ project_home }}; gulp serve"
